### ISSUE TITLE
Recomendação em UsuarioLogin

### ISSUE THREAD

**Issue by GustavoBoaz** [Lillow/Projeto-Blog-Pessoal-Back#5]
No documento **UsuarioLogin.java**:

- [x]  Colocar atributos de acordo com o exemplo abaixo
- [x] Incluir Getter e setter de todos eles

exemplo:
```java
private long id;
private String nome;
private String usuario;
private String foto;
private String senha;
private String token;
```

**Comment by Lillow** [comment]
task: fix in userLogin.
